#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 1 -w 1000 \
        s6-setuidgid abc \
            /usr/bin/code tunnel \
                --accept-server-license-terms \
                --cli-data-dir /config/data \
                --name "${TUNNEL_NAME}"
