#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        s6-setuidgid abc \
            /app/vscode_cli/code tunnel \
                --accept-server-license-terms \
                --cli-data-dir /config/data \
                --name "${MACHINE_NAME}"
