name: "Build-push docker image for latest"
on:
  [workflow_dispatch]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tibor309
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push image for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: tibor309/code-tunnel:amd64-latest
      
      - name: Build and push image for aarch64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile.aarch64
          push: true
          tags: tibor309/code-tunnel:arm64v8-latest
