name: "Build and push docker image to latest"
on:
  [workflow_dispatch]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          provenance: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ secrets.DEV_REPO }}:latest-amd64
      
      - name: Build and push image for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile.aarch64
          push: true
          provenance: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ secrets.DEV_REPO }}:latest-arm64

      - name: Create image manifest with latest tag
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/code-tunnel:latest \
            --amend ghcr.io/${{ github.repository_owner }}/${{ secrets.DEV_REPO }}:latest-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/${{ secrets.DEV_REPO }}:latest-arm64

      - name: Push image manifest
        run: |
          docker manifest push ghcr.io/${{ github.repository_owner }}/code-tunnel:latest
